SECRET_KEY = 'THIS IS A SECRET KEY, MAYBE. DO NOT TELL ANYONE!'
SEND_FILE_MAX_AGE_DEFAULT = 5

SQLALCHEMY_DATABASE_URI = 'mysql://root:suojiafen32@localhost:3306/kkgumi'
SQLALCHEMY_TRACK_MODIFICATIONS = True

QUEST_TYPES = ["ARTICLE", "TRANSLATION", "PROOFREADING", "TYPESETTING"]
RESOURCE_FOLDER = "resource/"
