SECRET_KEY = 'THIS IS A SECRET KEY, MAYBE. DO NOT TELL ANYONE!'

SQLALCHEMY_DATABASE_URI = 'mysql://root:suojiafen32@localhost:3306/kkgumi'
SQLALCHEMY_TRACK_MODIFICATIONS = True

QUEST_TYPES = ["ARTICLE", "REVIEW"]
RESOURCE_FOLDER = "resource/"
